In [10]:
import numpy as np
a = np.random.randn(1,60)

b = np.squeeze(a)
print( a)
print(b)

[[  5.79872775e-01  -8.24195222e-01  -2.04741085e-01   7.09194713e-01
    1.00285339e-01   2.13059562e-01  -7.29375281e-01   2.37732418e+00
   -1.03886175e+00   8.35630852e-01   1.44923866e+00  -2.40165792e+00
    7.31553513e-02  -1.75193851e+00   1.02671021e+00  -1.87185924e+00
   -2.60252920e-01   4.32118951e-02   4.17885131e-01  -3.93455906e-01
    1.42393272e+00  -1.59775825e+00  -2.31472966e-01  -8.30305593e-01
   -1.90442606e-03   2.82545643e-01   4.28877870e-01   1.01951921e+00
    1.29484936e+00  -6.09384148e-01  -4.63945616e-01  -4.65952990e-01
   -6.76461161e-02  -5.68614512e-01  -3.62572758e-01   2.77868322e-03
   -9.94751441e-01   3.94654251e-01  -1.52289947e+00   8.20376327e-01
    1.21092322e-01  -1.39603727e-01  -9.82247037e-01  -9.21202054e-02
    8.64312301e-01  -2.13402122e+00   1.24766884e+00   1.08555172e+00
    2.59538445e-02  -1.42411477e+00   6.18826911e-01   2.21664201e-01
    8.87035971e-01   8.76679142e-02  -1.50980618e+00  -1.64271505e+00
   -1.15710599e+00  

In [2]:
m = np.random.randint(10,size=(1,3))
print(m)
n = np.random.randint(5,size = (3,1))
print(n)
print(np.dot(m,n))

[[0 5 1]]
[[3]
 [2]
 [1]]
[[11]]


In [20]:
print(m*n)

[[ 0  2 10]
 [ 0  0  0]
 [ 0  0  0]]


In [5]:
print(m[0,1])

5


### 

In [27]:
import requests as rq
import re
import pandas as pd
url='http://rate.tmall.com/list_detail_rate.htm?itemId=41464129793&sellerId=1652490016¤tPage=1'

myweb = rq.get(url)
myjson = re.findall('\"rateList\":(\[.*?\])\,\"tags\"',myweb.text)[0]

mytable = pd.read_json(myjson)
mytable.to_csv('mytable.txt')

mytable.to_excel('mytable.xls')

IndexError: list index out of range